# Generated by Django 4.0.3 on 2022-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
