# Generated by Django 4.0 on 2022-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0002_alter_jobposting_options_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
