# Generated by Django 4.0 on 2022-04-16 17:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0003_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
