# Generated by Django 4.0 on 2022-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0006_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='category',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='postings', to='job_postings.Category', verbose_name='Category'),
        ),
    ]
