# Generated by Django 3.2.13 on 2022-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0008_remove_jobposting_category_jobposting_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='postings', to='job_postings.Category', verbose_name='Categories'),
        ),
    ]
