# Generated by Django 3.2.13 on 2022-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0010_auto_20220417_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.CharField(default='', max_length=300, verbose_name='Short description'),
            preserve_default=False,
        ),
    ]
