# Generated by Django 3.2.13 on 2022-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0011_company_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='short_description',
            field=models.TextField(max_length=300, verbose_name='Short description'),
        ),
    ]
