# Generated by Django 3.2.13 on 2022-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0012_alter_company_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(default='', max_length=200, verbose_name='Salary'),
            preserve_default=False,
        ),
    ]
