# Generated by Django 3.2.13 on 2022-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220416_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='accentitem',
            name='image_side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5, verbose_name='Image side'),
        ),
    ]
